# Generated by Django 4.2.16 on 2024-11-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='question',
            name='sector',
            field=models.CharField(choices=[('general', 'General'), ('environmental', 'Environmental'), ('social', 'Social'), ('economic', 'Economic'), ('physical', 'Physical')], max_length=50),
        ),
    ]
